package com.systems.model;

import java.io.Serializable;
import java.util.Random;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Entity
@Table(name = "account_activation")
@EntityListeners(AuditingEntityListener.class)
public class AccountActivationEntity implements Serializable{

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name= "user_name")
	private String userName;
	
	@Column(name= "auto_generated_url")
	private String autoGeneratedUrl;

	@Column(name= "activated")
	private int activated;
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getAutoGeneratedUrl() {
		return autoGeneratedUrl;
	}

	public void setAutoGeneratedUrl() {
		Random rnd = new Random();
		Long n = 2901611005485458455L + (long)(rnd.nextDouble()*59854958534L);
		this.autoGeneratedUrl = String.valueOf(n);
	}

	public int getActivated() {
		return activated;
	}

	public void setActivated() {
		this.activated = 0;
	}
	
	
	
}
